[language-server.typst-lsp]
command = "typst-lsp"

[[language]]
name = "typst"
language-servers = ["typst-lsp"]

[language-server.nixd]
command = "nixd"

[[language]]
name = "nix"
language-servers = ["nixd"]
